<?php  //[STAMP] 70da96cf8362ed32282978f556f3b14a
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Phpunit_unit;

trait Phpunit_unitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
