<?php  //[STAMP] 234614ec734d215e23c1c25f0f92e993
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Phpunit_integration;

trait Phpunit_integrationTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
