<?php  //[STAMP] 8c5f0b2f16746f7bbec8a5e9d22c165e
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Phpunit_integration;

trait Phpunit_integrationTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
