<?php  //[STAMP] 8a2fea9bd1196ad9f271d93232488409
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Phpunit_unit;

trait Phpunit_unitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
